name: Run Tests

on:
  push:           # triggers on all pushes to any branch
  pull_request:   # triggers on all PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Make CLI tools executable
        run: |
          chmod +x ./node_modules/.bin/xo
          chmod +x ./node_modules/.bin/nyc
          chmod +x ./node_modules/.bin/ava

      - name: Run tests
        run: npm run test
